#api-profiles-external
server {
    listen 80 default;

    set $service_name api-profiles;
    server_name api-profiles.local;

    access_log /var/log/nginx/api-profiles-access.log;
    error_log  /var/log/nginx/api-profiles-error.log error;

    charset utf-8;

    location / {
      index index.php;
      try_files $uri /index.php$is_args$args;
    }

    location ~ \.txt {
        root /var/www/services/api-profiles/public/sms;
    }

    location /public/files/ {
        alias /var/www/services/api-profiles/public/files/;
    }

    location ~ \.php {
        fastcgi_pass    api-profiles:9000;
        fastcgi_read_timeout 300;
        fastcgi_param   HTTP_X_REQUEST_ID $request_id;
        fastcgi_param   SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include         fastcgi_params;
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,x-device-udid';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }
       add_header 'Access-Control-Allow-Origin' '*' always;
       add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    }

    # Symfony project document root:
    root /var/www/public;
    # Настройка nginx для пропуска больших запросов.
    client_max_body_size 512m;
}